### ISSUE TITLE
{     "message": "The method is not allowed for the requested URL." }

### ISSUE THREAD

**Issue by Abhinchand** [arsfutura/face-recognition#11]

**Comment by Abhinchand** [comment]
while running the app.py an error occur, a message will show in browser ,that's the method is not allowed for the requested url.
help me how to fix it

**Comment by ldulcic** [comment]
Hi @Abhinchand! `/face-recognition` endpoint accepts only `POST` requests, when you open it in browser you are sending `GET` request, that's why you're seeing this message.
