### ISSUE TITLE
ValueError: could not convert string to float: 'import'

### ISSUE THREAD

**Issue by tytomulyono** [arsfutura/face-recognition#13]
hello, when i try to train this code with this command 
python -m training.train -d images -e util\generate_embeddings.py

that show error this:
ValueError: could not convert string to float: 'import'

can u help me?
maybe i need example code for run train.py
thank you

**Comment by ldulcic** [comment]
Hi @tytomulyono!

You don't need to provide `-e` option if you provide `-d`, they are mutually exclusive.
Just try without `-e`:
```bash
python -m training.train -d images
```

Let me know if this works for you.

**Comment by tytomulyono** [comment]
![3](https://user-images.githubusercontent.com/10941403/80579414-30360300-8a34-11ea-87dc-27b3279861bf.JPG)
error this

**Comment by tytomulyono** [comment]
![1](https://user-images.githubusercontent.com/10941403/80579455-43e16980-8a34-11ea-92c2-bb4736fd9d29.JPG)
if i pass the line prewhiten=False 
to 
self.aligner = MTCNN(keep_all=True, thresholds=[0.6, 0.7, 0.9])

get error no images dettected.
i have image in images folder
![2](https://user-images.githubusercontent.com/10941403/80579554-73907180-8a34-11ea-97b3-7cb51f381f4e.JPG)

**Comment by ldulcic** [comment]
hey @tytomulyono,
Please install dependencies this way:
```bash
pip install -r requirements.txt
```
Try again after that.
