### ISSUE TITLE
Google Co lab importing face_recognition 

### ISSUE THREAD

**Issue by bilalimran1412** [arsfutura/face-recognition#14]
![image](https://user-images.githubusercontent.com/29264592/84474114-bab08a00-aca3-11ea-8b7a-8410bf89c9b1.png)
I am trying to run this project on co-lab so I made a dictionary of arguments. run the requirements.txt file 
![image](https://user-images.githubusercontent.com/29264592/84474266-006d5280-aca4-11ea-95df-29cb96b56419.png)

I did this too as it wasn't recognizing face_recogition 
![image](https://user-images.githubusercontent.com/29264592/84474349-209d1180-aca4-11ea-8b63-78dcb6ef0409.png)

**Comment by ldulcic** [comment]
Hi @bilalimran1412!
face-recognition is not published on PyPi, there is a plan to do that at some point but it requires some refactoring...I'm a little bit busy at the moment, but I'll look into running project in google colab sometimes next week and get back to you :)

**Comment by ldulcic** [comment]
Hi @bilalimran1412!
Is it required that you run this project in google colab? This is more a standalone framework which can be used for generating custom face recognition system based on your data. If you need to use it another project, the easiest way is to generate Docker image with your face recognition system API and accessing it through http. You can read the details in the README.
