### ISSUE TITLE
getting error while importing preprocessing

### ISSUE THREAD

**Issue by tejasnikam** [arsfutura/face-recognition#15]
I am trying about an hour i am getting below error while running training file
  File "training\train.py", line 10, in <module>
    from face_recognition import preprocessing, FaceFeaturesExtractor, FaceRecogniser
ImportError: cannot import name 'preprocessing' from 'face_recognition' (C:\Users\tejas\AppData\Local\Programs\Python\Python38\lib\site-packages\face_recognition\__init__.py)

**Comment by ldulcic** [comment]
Hi @tejasnikam!
Try running it this way:
```
python -m training.train [ARGS]
```
It should work.

**Comment by tejasnikam** [comment]
yes it is working with this modification
