### ISSUE TITLE
unable to install torch==1.2.0 and torchvision==0.4.0 on anaconda with pip install and python version =3.6 x64 bit

### ISSUE THREAD

**Issue by vinayak-parab** [arsfutura/face-recognition#16]
Can you please share how you installed torch and torchvision?

**Comment by ldulcic** [comment]
Hi @vinayak-parab!
Simple `pip install -r requirements.txt` still works for me. Could you please share error that you get?

**Comment by vinayak-parab** [comment]
Installed using the command below command:
pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html.

Worked for me on Anaconda Virtual env with Python version==3.6
