### ISSUE TITLE
using gpu?

### ISSUE THREAD

**Issue by crypt0miester** [arsfutura/face-recognition#25]
hey, do you have a version of this using gpu?

**Comment by ldulcic** [comment]
Hi @crypt0miester!
There is no support for the GPU at the moment, I do plan to add it in the future, it shouldn't be too much work.
PRs are welcome if you are willing to help me 😊

**Comment by crypt0miester** [comment]
I'll try my best. currently setting up my multiple amd rx 570. takes time and energy to build torch with it. lol

**Comment by crypt0miester** [comment]
for anyone reading this in the future. the code works amazingly in CPU. no need for a GPU.  

the time taken using a GPU for a small number of classes are higher than using CPU. you may argue that my GPU (RX 570) is old, but the reason the code does not need GPU is that you can retrain the model with older dataset. makes it much faster and convenient. 

thanks @ldulcic.

**Comment by ldulcic** [comment]
No problem @crypt0miester, glad you made it work 😊 
Is the library working good for you?

**Comment by crypt0miester** [comment]
yes, very well. Thank you very much. 

I have put a necessity of 30 images per class. 

Currently working on filtering "bad" images so that I get a good accuracy for future inference. So if bad probability of an image detected it would be removed and new images would be added. 

Been scratching my brain for hours.

Do you have an idea of how to implement that?

**Comment by ldulcic** [comment]
> Currently working on filtering "bad" images so that I get a good accuracy for future inference. So if bad probability of an image detected it would be removed and **new images would be added**.

@crypt0miester how do you decide which new images would you add?
