### ISSUE TITLE
No module name joblib

### ISSUE THREAD

**Issue by cavoidcodon** [arsfutura/face-recognition#27]
I got an issue when running ./task/train.sh /folders. It is "no module name joblib" in file train.py. I've run the command "pip install requirement.txt" before run the command to train. Then a uninstall joblib and install again but this issue still comming.

**Comment by ldulcic** [comment]
Hi @minhHieuTB! 

I couldn't reproduce it. Which python version do you use? Can you post output of `pip freeze` here?

**Comment by cavoidcodon** [comment]
> Hi @minhHieuTB!
> 
> I couldn't reproduce it. Which python version do you use? Can you post output of `pip freeze` here?

Hi, thanks for your response. The problem has been fixed. I use the python3 and pip3, so i change the "pip" in the command to install the dependencies package to "pip3" and it work
