### ISSUE TITLE
Feature extractor storing OR getting trained from multiple images of same class ?

### ISSUE THREAD

**Issue by BalajiB197** [arsfutura/face-recognition#8]
Nice Work!!
When I was running your project, I am curious to understand one part here.
For person1 when we have multiple images, we extract features from each image and finally, we will store the trained feature or we will store all the features for future prediction of model???

**Comment by ldulcic** [comment]
Hi @BalajiB197! 
I'm not sure what do you mean by "trained features", maybe weights of classifier?
In this project, we extract features for each image of each person, then we train Softmax classifier based on these features. We don't store any extracted features for future prediction, we just train classifier with them, only thing that's stored at the end are the weights of Softmax classifier. 
Does this answer your question?

**Comment by BalajiB197** [comment]
Hello @ldulcic 
I am referring to this [issue,](https://github.com/ageitgey/face_recognition/issues/238) here we are not training the data but we extract 128d features and we do face comparison by storing in DB.
The above approach works well, but there is an issue when we test with the same image which we used for extracting the feature by little zoomin/ zoomout the Euclidean distance value is very high.
It will be helpful if you can suggest any better approach.
Thanks

**Comment by ldulcic** [comment]
Hi @BalajiB197 
I've read the issue you linked, people there claim to get good performance by storing vectors in DB and doing comparison. I haven't tried that approach, but I think training a classifier on top of embedding vectors gives you faster inference, especially if you have very big dataset. On the other hand, classifier is not so easy to train and you have to retrain it every time you add new data to dataset. You should try both approaches and see what works best for you. I'll upgrade code in this repo for automatic classifier training sometimes soon, this may help you to build faster face recognition system.

**Comment by BalajiB197** [comment]
@ldulcic 
Thanks for your suggestions sure will give a try. 
Training classifier is a good approach but when we have millions of classes/individual faces its not a good idea to just to find one face among those thousand classes.

**Comment by ldulcic** [comment]
@BalajiB197 
I'm not sure I understand, but classification is not "taking one face among thousands". There are various types of classifiers, I was referring to softmax classifier which is used in this project, this classifier basically learns boundaries between classes which gives you much faster inference.
